# Generated by Django 4.1.8 on 2023-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_exifimage", "0002_advancediptcexifrendition_basicexifimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicexifimage",
            name="story",
            field=models.TextField(blank=True, null=True),
        ),
    ]
