# Generated by Django 4.1.8 on 2023-04-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtail_exifimage", "0003_alter_basicexifimage_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUploadAccessKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="oPQvvHUJKjYmbq8pWU6oeq6ISYTiv9QQexhI9draV15XFUMMgQdN8QvIrurW4Y9qBFZjmgdQ5IFIypMbqiYfcwmTtpbcGK7RXcP5nD7TBO8mOowC1qaczA5X7KydBkyyy9Z9a0tnX2iVu2tu8Qz081t40ZlMsQZBb0ePx8stq8U8F6lpuN8p2jGVZ0EqzsJtx8FZWhqJVNoK05ObpBkKHPg4RMeuhHwzaZgridf3q0X4KyepyAEOio0rWFGJVBI39AZLMYx1ecgHJySfCfovoAjXBuNqDCjvSPjADaChr3X7MjHPxyoPUdLQzWQFmOShYjZLhmXMfw4qIBwgP5U5BiUKH4e0zLZweljzYqQrTLL5KR9IWkUVJgNlB3Ebw4e7roR2HolJVGhhoEEqkCuLrOnziuxvq36igEVDoHlj4cQ71Gh5kwJTzFc5aqWP1hsveiBMYtqEpGVQrz6TYaFPtedCspAHtLCPGWGoPoxOiO90tcaWuD1SSYe1RjirwHJV",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
